# Use root/1234 as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: homework
    ports:
      - "3306:3306"